ci: add project version check before publish

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -27,6 +27,16 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install --upgrade hatch
+    - name: Check project version
+      run: |
+        PROJECT_VERSION=$(TERM=dumb hatch version)
+
+        if [ "$PROJECT_VERSION" != "${TAG_NAME#v}" ]; then
+          echo "Wrong project version, cannot release: $PROJECT_VERSION, ${TAG_NAME#v} expected"
+          exit 1
+        fi
+      env:
+        TAG_NAME: ${{ github.ref }}
     - name: Build package
       run: hatch build
     - name: Publish package
